/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 22-Aug-2024 13:30:07 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE core.accommodation_unit_category
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('core."accommodation_unit_category_id_seq"'::text)::regclass),	-- Jedinstveni identifikator.
	uname varchar NOT NULL,	-- Naziv
	sequence integer NULL   DEFAULT 0,	-- Poredak
	status integer NOT NULL   DEFAULT 1,	-- Aktivan zapis: 1, ostalo: 0
	active integer NOT NULL   DEFAULT 1,	-- Aktivan zapis: 1, ostalo: 0
	translation jsonb NULL,	-- Prijevodi spremljeni u JSON formatu
	created_by bigint NULL,	-- Korisnik koji je kreirao zapis.
	created_date timestamp with time zone NOT NULL   DEFAULT now(),	-- Dan i vrijeme kad je kreiran zapis
	modified_by bigint NULL,	-- Korisnik koji je ažurirao zapis
	modified_date timestamp with time zone NOT NULL   DEFAULT now()	-- Dan i vrijeme kad je ažuriran zapis
)
;
