openapi: 3.0.3
info:
  version: '1.0.0'
  title: 'eVisitor common'
  description: 'Api for e-services to request common from eVisitor'
paths:
  #################
  # Documents
  #################

  upload:
    post:
      tags:
        - documents
      summary: Upload evidence
      operationId: uploadEvidence
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: Document uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'

  download:
    get:
      tags:
        - documents
      summary: Download document
      operationId: downloadDocument
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
            format: int64
          description: parameter id
        - in: query
          required: true
          name: documentName
          schema:
            type: string
        - in: query
          required: true
          name: isInline
          schema:
            type: boolean
      responses:
        200:
          description: Document successfully downloaded
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary


components:
  schemas:
    DocumentResponse:
      title: DocumentResponse
      type: object
      properties:
        id:
          type: integer
          format: int64
        uuid:
          type: string
        documentName:
          type: string
          description: document name
          example: rjesenje.pdf
        fileSize:
          type: integer
          format: int64
          description: size of uploaded file

    # paging
    Paging:
      title: Paging
      type: object
      properties:
        limit:
          type: integer
          format: int32
          default: 25
        offset:
          type: integer
          format: int32
          default: 0
        orderBy:
          type: string
        direction:
          type: string

    PagingInfo:
      title: Paging
      type: object
      properties:
        length:
          type: integer
          format: int64
        pageSize:
          type: integer
          format: int32
        pageIndex:
          type: integer
          format: int32

    CommonGetRequest:
      title: CommonGetRequest
      type: object
      properties:
        id:
          type: integer
          format: int64

    CommonGetListRequest:
      title: CommonRequest
      type: object
      allOf:
        - $ref: '#/components/schemas/Paging'
      properties:
        searchTerm:
          type: string
        onlyActive:
          type: boolean
          default: true

    CommonGetListLimitedRequest:
      title: CommonRequest
      type: object
      properties:
        searchTerm:
          type: string
        onlyActive:
          type: boolean
          default: true
        orderBy:
          type: string
        direction:
          type: string