version: '3.8'
services:
  postgres:
    image: postgres:16.3
    command: postgres -c 'max_connections=250' -c 'shared_buffers=250MB'
    container_name: car-adverts
    restart: unless-stopped
    environment:
      - POSTGRES_USER=car-adverts
      - POSTGRES_PASSWORD=caradverts
    networks:
      - car-adverts-postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '1000:5432'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
networks:
  car-adverts-postgres:
    name: car-adverts-postgres