openapi: 3.0.3
info:
  version: '1.0.0'
  title: 'car-adverts'
  description: Some description
paths:
  #################
  # Authentication
  #################

  /authentication/auth/get-users:
    $ref: './authentication.yaml#/paths/get-users'

  /authentication/auth/authenticate:
    $ref: './authentication.yaml#/paths/authenticate'

  /authentication/auth/refresh-token:
    $ref: './authentication.yaml#/paths/refresh-token'

  /authentication/auth/logout:
    $ref: './authentication.yaml#/paths/logout'