openapi: 3.0.3
info:
  version: '1.0.0'
  title: 'car-adverts'
  description: Some description
paths:

  #################
  # Codebooks
  #################

  /codebooks/fuel-types:
    $ref: './codebooks.yaml#/paths/fuel-types'