openapi: 3.0.3
info:
  version: '1.0.0'
  title: 'car-adverts'
  description: Some description
paths:

  #################
  # CarAdverts
  #################

  /car/adverts:
    $ref: './car-adverts.yaml#/paths/car-adverts'

  /car/adverts-paged:
    $ref: './car-adverts.yaml#/paths/car-adverts-paged'

  /car/adverts/{id}:
    $ref: './car-adverts.yaml#/paths/car-advert'