openapi: 3.0.3
info:
  version: '1.0.0'
  title: 'car-adverts codebook'
  description: Some description
paths:
  #################
  # Authentication
  #################

  /authentication/auth/get-users:
    $ref: './authentication.yaml#/paths/get-users'

  /authentication/auth/authenticate:
    $ref: './authentication.yaml#/paths/authenticate'

  #################
  # CarAdverts
  #################

  /car/adverts:
    $ref: './car-adverts.yaml#/paths/car-adverts'

  /car/adverts/{id}:
    $ref: './car-adverts.yaml#/paths/car-advert'

  #################
  # Codebooks
  #################

  /codebooks/fuel-types:
    $ref: './codebooks.yaml#/paths/fuel-types'


components:
  schemas:
    ErrorResponse:
      type: object
      description: Standard error response
      properties:
        type:
          type: string
          description: identifier that categorizes the error
        title:
          type: string
          description: a brief, human-readable message about the error
        status:
          type: integer
          format: int32
          description: the HTTP response code (optional)
          example: 400
        detail:
          type: string
          description: a human-readable explanation of the error
        instance:
          type: string
          description: identifies the specific occurrence of the error
